### ISSUE TITLE
Compiling without cuda?

### ISSUE THREAD

**Issue by apt-get-nat** [mrphys/tensorflow-nufft#23]
I'm working in a daskhub environment without cuda, and when I try to import the library I get the error NotFoundError: libcudart.so.11.0: cannot open shared object file: No such file or directory. I'd rather not have to try to install libcudart on this environment; is there a way to perform the
_nufft_ops = tf.load_op_library(
     24   tf.compat.v1.resource_loader.get_path_to_datafile('_nufft_ops.so'))
operation without attempting to import the GPU version of the code, just a CPU implementation?

**Comment by jmontalt** [comment]
Hi @apt-get-nat , yes, I am aware of this issue. We can certainly fix it, but I haven't had the chance yet. Ideally we should try to load CUDA but fall back to CPU-only if not found. Core TensorFlow has some kind of mechanism to do that. I'll see if I can find out how it works and whether we can do something similar.

Another approach might be to compile two versions of the library and release a separate CPU-only version, but the former option seems the better one to me. Either way, I'll keep this in mind for the next release.

As a temporary solution, you could try and build from source by removing the relevant parts from the Makefile, or maybe try a hack [like this](https://stackoverflow.com/questions/20777596/is-it-possible-to-bypass-shared-library-dependencies-required-for-an-already-com). If you do attempt to compile it without the CUDA bits, I'm happy to try and answer any questions.

**Comment by jmontalt** [comment]
@apt-get-nat just adding that you can also consider [using Docker](https://www.tensorflow.org/install/docker). TensorFlow standard images bring CUDA preinstalled so you wouldn't need to install anything on your system (other than Docker itself, of course). TensorFlow NUFFT has been tested with these images and is known to work.

FYI, for a more permanent solution I believe we can fix this by using static linking to the CUDA runtime library. I think this is what 
 [TF addons](https://github.com/tensorflow/addons) is doing.

I'll keep this thread updated with any progress.

**Comment by apt-get-nat** [comment]
Thanks! Long term, trying to load cuda and falling back on CPU routines seems like a great solution. For now I'm going to try mucking around in the Makefile and see if I can get it to compile for myself.

**Comment by apt-get-nat** [comment]
Goodness, of course. I don't know why I expected pip to do the make itself as well. Brain was just broken yesterday I guess. Thank you for your patience.

I noticed your makefile has a CUDA boolean; I was hoping that it would have all the cuda lines nested in IF statements so that compiling a cpu version would be relatively straightforward. Unfortunately, the nvcc calls themselves are not conditioned on the CUDA variable.

Do you think it would be feasible for me to compile those files with g++ and the CXXFLAGS instead of the CUFLAGS?

**Comment by jmontalt** [comment]
Actually, my first suggestion would be to replace the following line:

https://github.com/mrphys/tensorflow-nufft/blob/021090141fa7a6165b6cba5824c70659f506b644/Makefile#L93

By:

```
LDFLAGS += -l:libcudart_static.so
```

The `-lnvToolsExt` flag shouldn't be necessary. This is a potential fix I was planning to try, but haven't had the chance to verify it yet. I might have some time tomorrow though.

The idea is to replace the dynamic link to the CUDA runtime library by a static one, so that the application can run in systems without a CUDA installation.

The use of NVCC during compilation shouldn't be a problem (with this method, you do need to have a CUDA installation with NVCC in the system where you do the compilation, but this should not be necessary in the system where you run it). If you use the devcontainer as I suggested before, that takes care of everything you need to compile successfully (and does not install anything to your system except Docker).

Naturally, if you're going to be compiling with this method in the same system where you plan to run it, the whole thing is pointless, as once you've installed Docker you might as well run the existing TF NUFFT package as I also suggested before. But if you're going to be using a different computer, go ahead.

It should also be possible to do as you suggest and avoid compiling any CUDA files and using NVCC, but I'm not sure it's worth going down that route.

**Comment by jmontalt** [comment]
Hi @apt-get-nat, I have some good news and some bad news.

The good news is I think I fixed the issue by linking to the static CUDA libraries.

The bad news is that linking to the static CUDA libraries results in wheels above 100 MB, the size limit on PyPI, so I can't release. Cufft seems to be the main culprit.

My plan is to try and reduce the size of the binaries. Failing that, I'll request a size limit increase to PyPI. Failing that, we'll need to find a different solution.

In the meantime, you can checkout the develop branch and compile as I described earlier.

**Comment by apt-get-nat** [comment]
Hi,

Oh, that is good news! Just again, I really appreciate that this seems to be high on your priority list. I hope that getting it up to PyPi works out. Unfortunately, I can't do the compile on my local machine as described  to try it myself because the docker build command that vscode attempts to execute yields the error

`#5 15.26 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#5 15.26 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is no longer signed.
------
executor failed running [/bin/sh -c apt-get update &&     apt-get install -y lib cairo2-dev libgirepository1.0-dev libgtk-3-dev]: exit code: 100`

I'm familiar with adding public keys for apt-get in linux distros but I have no idea how to go about that for a docker container, or if that's even the problem here.

**Comment by jmontalt** [comment]
That should not have happened. The problem was in `apt-get update`. The error might be related to https://github.com/NVIDIA/nvidia-docker/issues/1632.

Will update here once I have more info.

**Comment by jmontalt** [comment]
The GPG error happened because NVIDIA recently updated the signing keys used by `apt` (more info [here](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/)). Anyway, this has been fixed in the latest release, so you might want to give the compilation another go! It should be possible to uncomment the following line to avoid CUDA errors:

https://github.com/mrphys/tensorflow-nufft/blob/07745e4850c68dac2de8a8381cc1181bfd17b1d8/Makefile#L95

You may also need to change the order by moving the following line:

https://github.com/mrphys/tensorflow-nufft/blob/07745e4850c68dac2de8a8381cc1181bfd17b1d8/Makefile#L86

**below** this block:

https://github.com/mrphys/tensorflow-nufft/blob/07745e4850c68dac2de8a8381cc1181bfd17b1d8/Makefile#L88-L97

As for a more permanent fix, I think it's not a good idea to increase the binary size for 200 MB for something no one's going to use anyway (unused by CPU implementation, already available in CUDA installation for GPU users). I think that'd be a hard sell to the PyPI maintainers. I'm also not a fan of adding a CPU only package, as that means another package to maintain.

Most importantly, I think all of this might become unnecessary once #24 has been addressed. Using the stream executor for the FFT, we should be able to remove the explicit cuFFT dependency (as it will be called implicitly by the TensorFlow framework).

**Comment by apt-get-nat** [comment]
That makes sense. The docker environment was able to get a little further before getting stuck again, this time on
```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/.X11-unix.
```
It seems like I might have to just wait for the issue 24 fix, and hope I can install that version on the dev machine.

**Comment by jmontalt** [comment]
You're almost there. The Docker image was built successfully, but it failed to run the container because the path `/tmp/.X11-unix` does not exist on your system. Fortunately, you don't need that to compile!

You can simply comment out the following line in `devcontainer.json`:

https://github.com/mrphys/tensorflow-nufft/blob/07745e4850c68dac2de8a8381cc1181bfd17b1d8/.devcontainer/devcontainer.json#L18

Hopefully, the container will then be able to start!

**Comment by apt-get-nat** [comment]
Just checking to confirm in that v0.8.0 did work great for me; thank you!

**Comment by jmontalt** [comment]
I wasn't expecting that, but great! v8.0 still may not work

**Comment by jmontalt** [comment]
This has been fully addressed starting with v8.1.0.
